[project]
authors = ["govindansriram <sriramgovindanwork@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojogpu"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
main = "mojo run src/mojogpu.mojo"
tests = "mojo test -I src test"

[dependencies]
max = "*"
